// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lomzirgbwqkdeumgviab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbXppcmdid3FrZGV1bWd2aWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjE0OTksImV4cCI6MjA3MDk5NzQ5OX0.SmqD02QfBj6SBrloThGFnLvBEqw3KlioRjkx3Q784zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});